/**
 * seed/llms.ts — Default seed data for the LLMs collection.
 * Aligned with: engine_v2/llms/
 */

export const llmsData = [
  {
    name: 'qwen2.5:0.5b',
    displayName: 'Qwen 2.5 0.5B',
    provider: 'ollama',
    description:
      'Ultra-lightweight Qwen model. Extremely fast inference with minimal resource usage. Good for quick drafts and simple Q&A tasks.',
    useCases: ['Quick Q&A', 'Draft Generation', 'Low-resource Deployment'],
    languages: 'en, zh, ja, ko, fr, de, es',
    parameterSize: '494M',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    minRamGb: 1,
    quantization: 'Q4_K_M',
    isFree: true,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    isDefault: false,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    name: 'qwen3.5:9b',
    displayName: 'Qwen 3.5 9B',
    provider: 'ollama',
    description:
      'Latest Qwen 3.5 series with strong reasoning and multilingual capabilities. Excellent balance of quality and speed for RAG workloads.',
    useCases: ['RAG Q&A', 'Complex Analysis', 'Reasoning', 'Report Generation'],
    languages: 'en, zh, ja, ko, fr, de, es, ar',
    parameterSize: '9.7B',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    minRamGb: 8,
    quantization: 'Q4_K_M',
    isFree: true,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    isDefault: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    name: 'qwen3.5:4b',
    displayName: 'Qwen 3.5 4B',
    provider: 'ollama',
    description:
      'Compact Qwen 3.5 model. Fast inference with good quality for general tasks. Ideal for question generation and structured output.',
    useCases: ['General Q&A', 'Question Generation', 'Fast Processing'],
    languages: 'en, zh, ja, ko, fr, de, es, ar',
    parameterSize: '4.7B',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    minRamGb: 4,
    quantization: 'Q4_K_M',
    isFree: true,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    isDefault: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    name: 'gpt-4o-mini',
    displayName: 'GPT-4o Mini',
    provider: 'azure_openai',
    description:
      'Fast and affordable Azure OpenAI model. Excellent for structured output (JSON), question generation, and general Q&A. 128K context window.',
    useCases: ['RAG Q&A', 'Question Generation', 'Structured Output', 'Fast Processing'],
    languages: 'All major languages',
    parameterSize: 'Unknown',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    minRamGb: 0,
    quantization: 'N/A (Cloud)',
    isFree: false,
    costPer1kInput: 0.00015,
    costPer1kOutput: 0.0006,
    isDefault: true,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    name: 'gpt-4o',
    displayName: 'GPT-4o',
    provider: 'azure_openai',
    description:
      "OpenAI's flagship model. Top-tier quality across all tasks. Requires Azure OpenAI API key.",
    useCases: ['All Tasks', 'Complex Reasoning', 'High Quality Output'],
    languages: 'All major languages',
    parameterSize: 'Unknown',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    minRamGb: 0,
    quantization: 'N/A (Cloud)',
    isFree: false,
    costPer1kInput: 0.0025,
    costPer1kOutput: 0.01,
    isDefault: false,
    isEnabled: true,
    sortOrder: 5,
  },
]
