/**
 * seed/llms.ts — Default seed data for the LLMs collection.
 * Aligned with: engine_v2/llms/
 */

export const llmsData = [
  {
    name: 'qwen2.5:14b',
    displayName: 'Qwen 2.5 14B',
    provider: 'ollama',
    description:
      'Larger Qwen model with improved reasoning and analytical capabilities. Better for complex questions requiring deep understanding.',
    useCases: ['Complex Analysis', 'RAG Q&A', 'Report Generation', 'Reasoning'],
    languages: 'en, zh, ja, ko, fr, de, es',
    parameterSize: '14B',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    minRamGb: 10,
    quantization: 'Q4_K_M',
    isFree: true,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    isDefault: false,
    isEnabled: true,
    sortOrder: 1,
  },
  {
    name: 'llama3.1:8b',
    displayName: 'Llama 3.1 8B',
    provider: 'ollama',
    description:
      "Meta's open-source model. Strong English performance, good for general Q&A. Fast inference speed.",
    useCases: ['General Q&A', 'English Content', 'Fast Processing'],
    languages: 'en, de, fr, it, pt, hi, es, th',
    parameterSize: '8B',
    contextWindow: 131072,
    maxOutputTokens: 4096,
    minRamGb: 6,
    quantization: 'Q4_K_M',
    isFree: true,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    isDefault: false,
    isEnabled: true,
    sortOrder: 2,
  },
  {
    name: 'deepseek-r1:8b',
    displayName: 'DeepSeek R1 8B',
    provider: 'ollama',
    description:
      'Specialized in reasoning and step-by-step problem solving. Shows chain-of-thought process. Excellent for analysis mode.',
    useCases: ['Reasoning', 'Step-by-step Analysis', 'Math', 'Logic'],
    languages: 'en, zh',
    parameterSize: '8B',
    contextWindow: 65536,
    maxOutputTokens: 8192,
    minRamGb: 6,
    quantization: 'Q4_K_M',
    isFree: true,
    costPer1kInput: 0,
    costPer1kOutput: 0,
    isDefault: false,
    isEnabled: true,
    sortOrder: 3,
  },
  {
    name: 'gpt-4o-mini',
    displayName: 'GPT-4o Mini',
    provider: 'azure_openai',
    description:
      'Fast and affordable Azure OpenAI model. Excellent for structured output (JSON), question generation, and general Q&A. 128K context window.',
    useCases: ['RAG Q&A', 'Question Generation', 'Structured Output', 'Fast Processing'],
    languages: 'All major languages',
    parameterSize: 'Unknown',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    minRamGb: 0,
    quantization: 'N/A (Cloud)',
    isFree: false,
    costPer1kInput: 0.00015,
    costPer1kOutput: 0.0006,
    isDefault: true,
    isEnabled: true,
    sortOrder: 4,
  },
  {
    name: 'gpt-4o',
    displayName: 'GPT-4o',
    provider: 'azure_openai',
    description:
      "OpenAI's flagship model. Top-tier quality across all tasks. Requires Azure OpenAI API key.",
    useCases: ['All Tasks', 'Complex Reasoning', 'High Quality Output'],
    languages: 'All major languages',
    parameterSize: 'Unknown',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    minRamGb: 0,
    quantization: 'N/A (Cloud)',
    isFree: false,
    costPer1kInput: 0.0025,
    costPer1kOutput: 0.01,
    isDefault: false,
    isEnabled: true,
    sortOrder: 5,
  },
]
